### ISSUE TITLE
Fix ru-RU

### ISSUE THREAD

**Issue by dspancov** [willsp/polyfill-Number.toLocaleString-with-Locales#14]
Added

var transformForLocale = {
    ....
    "ru": spaceThousCommaDec,
    "ru-RU": spaceThousCommaDec,

**Comment by willsp** [comment]
Please submit a pull request...

**Comment by dspancov** [comment]
https://github.com/willsp/polyfill-Number.toLocaleString-with-Locales/pull/19

**Comment by willsp** [comment]
Merged and updated in npm registry. Thanks!!!
