### ISSUE TITLE
maximumFractionDigits doesn't work without  minimumFractionDigits

### ISSUE THREAD

**Issue by Preeternal** [willsp/polyfill-Number.toLocaleString-with-Locales#22]
```js
const optionsN = {
      style: 'currency',
      currencyDisplay: 'symbol',
      currency: radio_props[this.props.radio].index,
      //minimumFractionDigits: 2,
      maximumFractionDigits: 2
    };
```
![default](https://user-images.githubusercontent.com/24249735/36614455-7290bb40-18e5-11e8-8dba-12d8c43b9905.png)

```js
const optionsN = {
      style: 'currency',
      currencyDisplay: 'symbol',
      currency: radio_props[this.props.radio].index,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    };
```
![default](https://user-images.githubusercontent.com/24249735/36614582-dd40aec8-18e5-11e8-9c76-a8f7c1923d22.png)

**Comment by willsp** [comment]
Sorry, unfortunately, like I said, this is nowhere near complete. I didn't implement that feature, and am not likely to do so. If you can, and are willing to implement it, I'll take a look at your pull request.
