### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by monolithed** [willsp/polyfill-Number.toLocaleString-with-Locales#6]
Could you publish the one?

**Comment by willsp** [comment]
Yea, i can probably do that... Though, I think it will be more appropriate as a bower module... I'll look into it. 

Thanks

**Comment by monolithed** [comment]
npm package will be more convenient for polyfill combinators like [Polyfiller](https://github.com/Polyfiller/polyfiller) as well :)

**Comment by willsp** [comment]
Published as number-to-locale-string.
